/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Bond, StateMetrics, CorpCategory, CreditRating, RatingAgency } from './types';

// Seeded list of 52 municipal bonds of India
export const INITIAL_BONDS: Bond[] = [
  // Maharashtra
  {
    id: 'BND-BMC-001',
    corporationName: 'Brihanmumbai Municipal Corporation',
    shortName: 'BMC',
    state: 'Maharashtra',
    bondId: 'BMC-780-AM28',
    faceValue: 100000,
    currentPrice: 101450,
    yieldPercent: 7.42,
    rating: 'AAA',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-11-15',
    change24h: 0.15,
    volume: 450.5,
    category: 'Metro',
    couponPercent: 7.80,
    paymentFrequency: 'Semi-Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Coastal Road Phase-1', 'Goregaon-Mulund Link Road', 'Bhandup Water Treatment Plant'],
    capitalRaisedCr: 500,
    description: 'Secured by escrow of octroi/grant-in-aid receipts and property tax collections. Highly liquid and premium municipal paper.',
    allTimeHigh: 102100,
    allTimeLow: 99400
  },
  {
    id: 'BND-BMC-002',
    corporationName: 'Brihanmumbai Municipal Corporation',
    shortName: 'BMC',
    state: 'Maharashtra',
    bondId: 'BMC-815-ST32',
    faceValue: 100000,
    currentPrice: 102100,
    yieldPercent: 7.78,
    rating: 'AAA',
    ratingAgency: 'ICRA',
    maturityDate: '2032-04-10',
    change24h: -0.05,
    volume: 320.0,
    category: 'Metro',
    couponPercent: 8.15,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Middle Vaitarna Drinking Water', 'Sewage Treatment Plants (WwTF)'],
    capitalRaisedCr: 800,
    description: 'Long-term bonds issued for heavy capital expenditure in water security and ecological sanitization.',
    allTimeHigh: 103200,
    allTimeLow: 100100
  },
  {
    id: 'BND-PCMC-001',
    corporationName: 'Pimpri Chinchwad Municipal Corporation',
    shortName: 'PCMC',
    state: 'Maharashtra',
    bondId: 'PCMC-820-SE29',
    faceValue: 100000,
    currentPrice: 100340,
    yieldPercent: 8.12,
    rating: 'AA+',
    ratingAgency: 'CRISIL',
    maturityDate: '2029-09-30',
    change24h: 0.45,
    volume: 180.2,
    category: 'Metro',
    couponPercent: 8.20,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Metro Line Extension Link', 'Smart City Solid Waste Hub'],
    capitalRaisedCr: 200,
    description: 'Backed by robust property tax collections in Pune industrial corridors and escrow arrangement.',
    allTimeHigh: 101850,
    allTimeLow: 98900
  },
  {
    id: 'BND-NMMC-001',
    corporationName: 'Navi Mumbai Municipal Corporation',
    shortName: 'NMMC',
    state: 'Maharashtra',
    bondId: 'NMMC-795-FB27',
    faceValue: 100000,
    currentPrice: 99820,
    yieldPercent: 8.01,
    rating: 'AA+',
    ratingAgency: 'CARE',
    maturityDate: '2027-02-18',
    change24h: -0.12,
    volume: 240.8,
    category: 'Metro',
    couponPercent: 7.95,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Navi Mumbai Smart LED Lighting', 'E-Bus Charging Terminals'],
    capitalRaisedCr: 150,
    description: 'Highly liquid bonds with active market makers. Navi Mumbai is among the strongest financial corporations.',
    allTimeHigh: 100900,
    allTimeLow: 99100
  },
  {
    id: 'BND-PMC-001',
    corporationName: 'Pune Municipal Corporation',
    shortName: 'PMC',
    state: 'Maharashtra',
    bondId: 'PMC-824-OC30',
    faceValue: 100000,
    currentPrice: 101200,
    yieldPercent: 7.95,
    rating: 'AA',
    ratingAgency: 'CARE',
    maturityDate: '2030-10-15',
    change24h: 0.08,
    volume: 110.5,
    category: 'Metro',
    couponPercent: 8.24,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Mula-Mutha River Rejuvenation', 'Smart BRTS Corridor'],
    capitalRaisedCr: 250,
    description: 'Reputable green bonds designed strictly for environmental sustainability projects.',
    allTimeHigh: 101900,
    allTimeLow: 99500
  },

  // Karnataka
  {
    id: 'BND-BBMP-001',
    corporationName: 'Bruhat Bengaluru Mahanagara Palike',
    shortName: 'BBMP',
    state: 'Karnataka',
    bondId: 'BBMP-850-DE28',
    faceValue: 100000,
    currentPrice: 102400,
    yieldPercent: 7.85,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-12-20',
    change24h: 0.32,
    volume: 290.0,
    category: 'Metro',
    couponPercent: 8.50,
    paymentFrequency: 'Semi-Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Hebbal Flyover De-bottlenecking', 'Storm Water Drain (Kaluve) Desilting'],
    capitalRaisedCr: 300,
    description: 'Secured by pledge of commercial property leases and escrow of advertisement tax revenues.',
    allTimeHigh: 103100,
    allTimeLow: 100500
  },
  {
    id: 'BND-BBMP-002',
    corporationName: 'Bruhat Bengaluru Mahanagara Palike',
    shortName: 'BBMP',
    state: 'Karnataka',
    bondId: 'BBMP-790-JA31',
    faceValue: 100000,
    currentPrice: 99550,
    yieldPercent: 8.01,
    rating: 'AA',
    ratingAgency: 'ICRA',
    maturityDate: '2031-01-15',
    change24h: -0.18,
    volume: 155.0,
    category: 'Metro',
    couponPercent: 7.90,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Whitefield Area Traffic Re-routing', 'Tender SURE Urban Roads'],
    capitalRaisedCr: 400,
    description: 'Structured debt with solid reserve mechanism and a dedicated sinking fund for redemption.',
    allTimeHigh: 101100,
    allTimeLow: 98700
  },

  // Gujarat
  {
    id: 'BND-AMC-001',
    corporationName: 'Ahmedabad Municipal Corporation',
    shortName: 'AMC',
    state: 'Gujarat',
    bondId: 'AMC-770-JU27',
    faceValue: 100000,
    currentPrice: 100750,
    yieldPercent: 7.40,
    rating: 'AA+',
    ratingAgency: 'CRISIL',
    maturityDate: '2027-06-18',
    change24h: 0.11,
    volume: 410.0,
    category: 'Metro',
    couponPercent: 7.70,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Sabarmati Riverfront Phase-2', 'BRTS Janmarg expansion'],
    capitalRaisedCr: 200,
    description: 'The pioneer of Indian municipal bonds. Legendary credit discipline and highly supportive state policy framework.',
    allTimeHigh: 101800,
    allTimeLow: 99800
  },
  {
    id: 'BND-SMC-001',
    corporationName: 'Surat Municipal Corporation',
    shortName: 'SMC',
    state: 'Gujarat',
    bondId: 'SMC-810-AP29',
    faceValue: 100000,
    currentPrice: 101150,
    yieldPercent: 7.68,
    rating: 'AA+',
    ratingAgency: 'CARE',
    maturityDate: '2029-04-25',
    change24h: 0.05,
    volume: 215.5,
    category: 'Metro',
    couponPercent: 8.10,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Tapi Riverfront Rejuvenation', 'Solar Rooftop Aggregators'],
    capitalRaisedCr: 250,
    description: 'Surat enjoys high-grade credit status owing to zero debt history and stellar property tax collectors.',
    allTimeHigh: 102000,
    allTimeLow: 99400
  },
  {
    id: 'BND-VMC-001',
    corporationName: 'Vadodara Municipal Corporation',
    shortName: 'VMC',
    state: 'Gujarat',
    bondId: 'VMC-840-NV29',
    faceValue: 100000,
    currentPrice: 100900,
    yieldPercent: 8.15,
    rating: 'AA',
    ratingAgency: 'ICRA',
    maturityDate: '2029-11-20',
    change24h: 0.28,
    volume: 95.0,
    category: 'Tier-2',
    couponPercent: 8.40,
    paymentFrequency: 'Semi-Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Vishwamitri River Management', 'Vadodara Intelligent Traffic System'],
    capitalRaisedCr: 100,
    description: 'Backed by water cess receipts under structured state escrows.',
    allTimeHigh: 101500,
    allTimeLow: 99300
  },

  // Telangana
  {
    id: 'BND-GHMC-001',
    corporationName: 'Greater Hyderabad Municipal Corporation',
    shortName: 'GHMC',
    state: 'Telangana',
    bondId: 'GHMC-825-MR28',
    faceValue: 100000,
    currentPrice: 101800,
    yieldPercent: 7.55,
    rating: 'AA',
    ratingAgency: 'CARE',
    maturityDate: '2028-03-31',
    change24h: 0.19,
    volume: 380.0,
    category: 'Metro',
    couponPercent: 8.25,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['SRDP (Strategic Road Dev Program)', 'Musilink Sewage Restructuring'],
    capitalRaisedCr: 400,
    description: 'Guaranteed by Telangana State Government backing with a structured escrow on land transfer fees.',
    allTimeHigh: 102400,
    allTimeLow: 100100
  },
  {
    id: 'BND-GHMC-002',
    corporationName: 'Greater Hyderabad Municipal Corporation',
    shortName: 'GHMC',
    state: 'Telangana',
    bondId: 'GHMC-890-ST30',
    faceValue: 100000,
    currentPrice: 103900,
    yieldPercent: 7.90,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2030-09-15',
    change24h: 0.12,
    volume: 175.4,
    category: 'Metro',
    couponPercent: 8.90,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Skyway Flyover Systems', 'Charminar Pedestrian Expansion'],
    capitalRaisedCr: 500,
    description: 'Provides superior coupon yields. Subscribed largely by domestic pension funds.',
    allTimeHigh: 104500,
    allTimeLow: 101200
  },

  // Tamil Nadu
  {
    id: 'BND-CMC-001',
    corporationName: 'Greater Chennai Corporation',
    shortName: 'GCC',
    state: 'Tamil Nadu',
    bondId: 'GCC-795-OC28',
    faceValue: 100000,
    currentPrice: 99900,
    yieldPercent: 7.98,
    rating: 'AA+',
    ratingAgency: 'ICRA',
    maturityDate: '2028-10-18',
    change24h: -0.04,
    volume: 220.0,
    category: 'Metro',
    couponPercent: 7.95,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Stormwater Drain Phase-III (Kovalam)', 'Smart Bin Fleet Procurement'],
    capitalRaisedCr: 200,
    description: 'Structured and debt serviced primarily through direct state allocation and localized property tax sweeps.',
    allTimeHigh: 101100,
    allTimeLow: 99200
  },
  {
    id: 'BND-COMC-001',
    corporationName: 'Coimbatore Municipal Corporation',
    shortName: 'CMC',
    state: 'Tamil Nadu',
    bondId: 'CMC-830-JL29',
    faceValue: 100000,
    currentPrice: 100250,
    yieldPercent: 8.21,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2029-07-22',
    change24h: 0.14,
    volume: 82.3,
    category: 'Tier-2',
    couponPercent: 8.30,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Coimbatore Smart City Solar Farm', 'Lake Restoration (Noyyal Grid)'],
    capitalRaisedCr: 80,
    description: 'Solid execution capacity. Coimbatore represents high industrial activity and tax collections.',
    allTimeHigh: 101200,
    allTimeLow: 98800
  },

  // Delhi
  {
    id: 'BND-NDMC-001',
    corporationName: 'New Delhi Municipal Council',
    shortName: 'NDMC',
    state: 'Delhi',
    bondId: 'NDMC-760-MY27',
    faceValue: 100000,
    currentPrice: 100800,
    yieldPercent: 7.21,
    rating: 'AAA',
    ratingAgency: 'CRISIL',
    maturityDate: '2027-05-15',
    change24h: -0.02,
    volume: 310.5,
    category: 'Metro',
    couponPercent: 7.60,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Cannaught Place Utility Ducts', 'Smart Grid Power Distribution'],
    capitalRaisedCr: 150,
    description: 'Premier status bond featuring elite central Delhi tax bases. Near zero default probability.',
    allTimeHigh: 101600,
    allTimeLow: 99900
  },
  {
    id: 'BND-SDMC-001',
    corporationName: 'South Delhi Municipal Corporation',
    shortName: 'SDMC',
    state: 'Delhi',
    bondId: 'SDMC-835-AU29',
    faceValue: 100000,
    currentPrice: 102150,
    yieldPercent: 7.85,
    rating: 'AA+',
    ratingAgency: 'CARE',
    maturityDate: '2029-08-10',
    change24h: 0.17,
    volume: 145.0,
    category: 'Metro',
    couponPercent: 8.35,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Okhla Waste-to-Energy Plant', 'Multi-level Robotic Parking Lots'],
    capitalRaisedCr: 250,
    description: 'Merged under the unified MCD. Retains strong ring-fenced escrow security for initial holders.',
    allTimeHigh: 102900,
    allTimeLow: 100200
  },

  // West Bengal
  {
    id: 'BND-KMC-001',
    corporationName: 'Kolkata Municipal Corporation',
    shortName: 'KMC',
    state: 'West Bengal',
    bondId: 'KMC-845-JN30',
    faceValue: 100000,
    currentPrice: 98110,
    yieldPercent: 8.85,
    rating: 'AA-',
    ratingAgency: 'ICRA',
    maturityDate: '2030-06-30',
    change24h: -0.22,
    volume: 130.4,
    category: 'Metro',
    couponPercent: 8.45,
    paymentFrequency: 'Semi-Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Heritage Zone LED Retrofits', 'Dhapa Landfill Bioremediation'],
    capitalRaisedCr: 200,
    description: 'Higher yield profile compensating for conservative municipal financial state guarantees.',
    allTimeHigh: 100200,
    allTimeLow: 97400
  },

  // Uttar Pradesh
  {
    id: 'BND-LMC-001',
    corporationName: 'Lucknow Municipal Corporation',
    shortName: 'LMC',
    state: 'Uttar Pradesh',
    bondId: 'LMC-850-NV28',
    faceValue: 100000,
    currentPrice: 101900,
    yieldPercent: 7.95,
    rating: 'AA',
    ratingAgency: 'INDIA RATINGS',
    maturityDate: '2028-11-25',
    change24h: 0.25,
    volume: 160.0,
    category: 'Tier-2',
    couponPercent: 8.50,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Gomti Riverfront solid waste collectors', 'Piped Gas Distribution grid'],
    capitalRaisedCr: 200,
    description: 'The first North Indian city bond carrying double state escrows and interest subsidy payouts.',
    allTimeHigh: 102500,
    allTimeLow: 99800
  },
  {
    id: 'BND-GNP-001',
    corporationName: 'Ghaziabad Municipal Corporation',
    shortName: 'GMC',
    state: 'Uttar Pradesh',
    bondId: 'GMC-810-DE27',
    faceValue: 100000,
    currentPrice: 100500,
    yieldPercent: 7.92,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2027-12-10',
    change24h: 0.18,
    volume: 115.0,
    category: 'Tier-2',
    couponPercent: 8.10,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Tertiary Sewage Water Supply to Industries', 'Indirapuram Rain Water Harvesting'],
    capitalRaisedCr: 150,
    description: 'First ever green bonds issued for specialized industrial tertiary water supply.',
    allTimeHigh: 101200,
    allTimeLow: 99600
  },
  {
    id: 'BND-KNP-001',
    corporationName: 'Kanpur Municipal Corporation',
    shortName: 'KNP',
    state: 'Uttar Pradesh',
    bondId: 'KNP-875-MR30',
    faceValue: 100000,
    currentPrice: 99200,
    yieldPercent: 8.92,
    rating: 'AA-',
    ratingAgency: 'CARE',
    maturityDate: '2030-03-25',
    change24h: -0.35,
    volume: 75.0,
    category: 'Tier-2',
    couponPercent: 8.75,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Jajmau Leather Cluster Waste Treatment', 'Road Overbridges'],
    capitalRaisedCr: 100,
    description: 'Provides strong interest payouts. Structurally secures capital through property tax escrow sweep accounts.',
    allTimeHigh: 100500,
    allTimeLow: 98100
  },

  // Madhya Pradesh
  {
    id: 'BND-IMC-001',
    corporationName: 'Indore Municipal Corporation',
    shortName: 'IMC',
    state: 'Madhya Pradesh',
    bondId: 'IMC-825-FB28',
    faceValue: 100000,
    currentPrice: 102800,
    yieldPercent: 7.45,
    rating: 'AA+',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-02-15',
    change24h: 0.52,
    volume: 205.8,
    category: 'Tier-2',
    couponPercent: 8.25,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Indore Green Solar Project (60MW)', 'Smart City Waste Segregators'],
    capitalRaisedCr: 244,
    description: 'Publicly traded green bond. Indore has highest cleanliness record in India, translating to phenomenal civic collections.',
    allTimeHigh: 103200,
    allTimeLow: 100100
  },
  {
    id: 'BND-BMC-MP001',
    corporationName: 'Bhopal Municipal Corporation',
    shortName: 'BHM',
    state: 'Madhya Pradesh',
    bondId: 'BHM-840-OC29',
    faceValue: 100000,
    currentPrice: 100600,
    yieldPercent: 8.23,
    rating: 'AA',
    ratingAgency: 'CARE',
    maturityDate: '2029-10-12',
    change24h: 0.08,
    volume: 90.5,
    category: 'Tier-2',
    couponPercent: 8.40,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Lake view development corridor', 'Bhopal Bus rapid trans scheme'],
    capitalRaisedCr: 175,
    description: 'Secured by dedicated stamp duty fee sharing mechanism with the MP State government.',
    allTimeHigh: 101400,
    allTimeLow: 99100
  },

  // Rajasthan
  {
    id: 'BND-JMC-001',
    corporationName: 'Jaipur Municipal Corporation',
    shortName: 'JMC',
    state: 'Rajasthan',
    bondId: 'JMC-830-JL29',
    faceValue: 100000,
    currentPrice: 100150,
    yieldPercent: 8.25,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2029-07-15',
    change24h: 0.03,
    volume: 110.0,
    category: 'Tier-2',
    couponPercent: 8.30,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Heritage Street Pedestrianization', 'Pink City Sewer Upgradation'],
    capitalRaisedCr: 120,
    description: 'Secured by Rajasthan state development grants and tourism cess escrow accounts.',
    allTimeHigh: 100900,
    allTimeLow: 99200
  },

  // Andhra Pradesh
  {
    id: 'BND-GVMC-001',
    corporationName: 'Greater Visakhapatnam Municipal Corporation',
    shortName: 'GVMC',
    state: 'Andhra Pradesh',
    bondId: 'GVMC-860-SE30',
    faceValue: 100000,
    currentPrice: 99750,
    yieldPercent: 8.65,
    rating: 'AA-',
    ratingAgency: 'ICRA',
    maturityDate: '2030-09-28',
    change24h: -0.15,
    volume: 125.0,
    category: 'Tier-2',
    couponPercent: 8.60,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Coastal Smart Drainage Infrastructure', 'Beach Road Beautification & Lighting'],
    capitalRaisedCr: 110,
    description: 'Backed by real estate developer approval fees and property tax allocations in key urban zones.',
    allTimeHigh: 101100,
    allTimeLow: 98500
  },

  // Punjab
  {
    id: 'BND-AMC-PB001',
    corporationName: 'Amritsar Municipal Corporation',
    shortName: 'AMR',
    state: 'Punjab',
    bondId: 'AMR-870-DE31',
    faceValue: 100000,
    currentPrice: 98900,
    yieldPercent: 8.91,
    rating: 'A+',
    ratingAgency: 'CARE',
    maturityDate: '2031-12-15',
    change24h: -0.42,
    volume: 68.0,
    category: 'Tier-3',
    couponPercent: 8.70,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Golden Temple Ring Road Refurbishment', 'Amritsar Green Park Swachh System'],
    capitalRaisedCr: 50,
    description: 'A higher risk asset priced attractively. Backed by structured temple area tourism cess and parking fee flows.',
    allTimeHigh: 100100,
    allTimeLow: 97800
  },
  {
    id: 'BND-LMC-PB001',
    corporationName: 'Ludhiana Municipal Corporation',
    shortName: 'LUD',
    state: 'Punjab',
    bondId: 'LUD-825-ST28',
    faceValue: 100000,
    currentPrice: 100400,
    yieldPercent: 8.12,
    rating: 'AA-',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-10-30',
    change24h: 0.05,
    volume: 82.0,
    category: 'Tier-2',
    couponPercent: 8.25,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Budha Nallah Pollution Interceptor', 'Industrial Zone Road Upgrades'],
    capitalRaisedCr: 100,
    description: 'Escrowed by heavy industry water taxation and property tax charges.',
    allTimeHigh: 101400,
    allTimeLow: 99100
  },

  // Haryana
  {
    id: 'BND-MCG-001',
    corporationName: 'Municipal Corporation of Gurugram',
    shortName: 'MCG',
    state: 'Haryana',
    bondId: 'MCG-790-ST28',
    faceValue: 100000,
    currentPrice: 101600,
    yieldPercent: 7.35,
    rating: 'AA+',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-06-15',
    change24h: 0.22,
    volume: 380.0,
    category: 'Metro',
    couponPercent: 7.90,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Gurugram Smart Water Grid', 'Automated Sewage Management Line'],
    capitalRaisedCr: 350,
    description: 'Unbelievably rich corporate and property tax base. Gurugram yields are close to corporate giants.',
    allTimeHigh: 102200,
    allTimeLow: 100050
  },
  {
    id: 'BND-MCF-001',
    corporationName: 'Municipal Corporation of Faridabad',
    shortName: 'MCF',
    state: 'Haryana',
    bondId: 'MCF-880-MR31',
    faceValue: 100000,
    currentPrice: 97600,
    yieldPercent: 9.25,
    rating: 'A',
    ratingAgency: 'CARE',
    maturityDate: '2031-03-31',
    change24h: -0.65,
    volume: 42.0,
    category: 'Tier-2',
    couponPercent: 8.80,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Industrial Sector Flyover', 'Rainwater Re-routing Grid'],
    capitalRaisedCr: 80,
    description: 'High yield potential compensating for historical capital constraints in Faridabad core infrastructure receipts.',
    allTimeHigh: 99800,
    allTimeLow: 96500
  },

  // Bihar
  {
    id: 'BND-PMC-BH001',
    corporationName: 'Patna Municipal Corporation',
    shortName: 'PAT',
    state: 'Bihar',
    bondId: 'PAT-920-FB30',
    faceValue: 100000,
    currentPrice: 99110,
    yieldPercent: 9.38,
    rating: 'A',
    ratingAgency: 'ICRA',
    maturityDate: '2030-02-15',
    change24h: -0.11,
    volume: 54.0,
    category: 'Tier-2',
    couponPercent: 9.20,
    paymentFrequency: 'Annual',
    taxStatus: 'Taxable',
    projectsFunded: ['Ganga Path Drainage Interceptors', 'Patna Smart Waste Hubs'],
    capitalRaisedCr: 120,
    description: 'Secured by Patna municipal tax collections with a 2x debt service coverage ratio backup.',
    allTimeHigh: 100800,
    allTimeLow: 97900
  },

  // Odisha
  {
    id: 'BND-BMC-OR001',
    corporationName: 'Bhubaneswar Municipal Corporation',
    shortName: 'BHU',
    state: 'Odisha',
    bondId: 'BHU-815-AU29',
    faceValue: 100000,
    currentPrice: 101100,
    yieldPercent: 7.82,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2029-08-20',
    change24h: 0.14,
    volume: 135.0,
    category: 'Tier-2',
    couponPercent: 8.15,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['E-Mobility smart transport grid', 'Kalinga Drainage Interceptors'],
    capitalRaisedCr: 100,
    description: 'Backed by outstanding fiscal prudence. Strong state support and tourism-led infrastructure cess.',
    allTimeHigh: 101800,
    allTimeLow: 99400
  },

  // Kerala
  {
    id: 'BND-TMC-KL001',
    corporationName: 'Thiruvananthapuram Municipal Corporation',
    shortName: 'TMC',
    state: 'Kerala',
    bondId: 'TMC-835-MY29',
    faceValue: 100000,
    currentPrice: 100350,
    yieldPercent: 8.24,
    rating: 'AA',
    ratingAgency: 'CARE',
    maturityDate: '2029-05-18',
    change24h: 0.05,
    volume: 98.2,
    category: 'Tier-2',
    couponPercent: 8.35,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Waterfront solar park network', 'Digital civic center expansions'],
    capitalRaisedCr: 100,
    description: 'Highly structured green issue carrying state level interest payment guarantees.',
    allTimeHigh: 101250,
    allTimeLow: 99100
  },
  {
    id: 'BND-KMC-KL001',
    corporationName: 'Kochi Municipal Corporation',
    shortName: 'KOC',
    state: 'Kerala',
    bondId: 'KOC-810-AP28',
    faceValue: 100000,
    currentPrice: 100800,
    yieldPercent: 7.85,
    rating: 'AA',
    ratingAgency: 'CRISIL',
    maturityDate: '2028-04-10',
    change24h: 0.09,
    volume: 120.0,
    category: 'Tier-2',
    couponPercent: 8.10,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Kochi Smart Water Ferry Jetty', 'Intelligent Waste Gasification'],
    capitalRaisedCr: 150,
    description: 'Backed by robust commercial tax yields in Kochi port zone circles.',
    allTimeHigh: 101600,
    allTimeLow: 99650
  },

  // Chhattisgarh
  {
    id: 'BND-RMC-CG001',
    corporationName: 'Raipur Municipal Corporation',
    shortName: 'RMC',
    state: 'Chhattisgarh',
    bondId: 'RMC-845-JL29',
    faceValue: 100000,
    currentPrice: 100200,
    yieldPercent: 8.38,
    rating: 'AA-',
    ratingAgency: 'ICRA',
    maturityDate: '2029-07-15',
    change24h: 0.11,
    volume: 78.5,
    category: 'Tier-2',
    couponPercent: 8.45,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Solid waste automatic material recovery', 'Smart drainage bypass grid'],
    capitalRaisedCr: 100,
    description: 'Sustained by mining cess royalty redistribution and municipal tax sweeps.',
    allTimeHigh: 101300,
    allTimeLow: 98900
  },

  // Uttarakhand
  {
    id: 'BND-DMC-UK001',
    corporationName: 'Dehradun Municipal Corporation',
    shortName: 'DDN',
    state: 'Uttarakhand',
    bondId: 'DDN-860-SE30',
    faceValue: 100000,
    currentPrice: 99400,
    yieldPercent: 8.75,
    rating: 'A+',
    ratingAgency: 'CRISIL',
    maturityDate: '2030-09-10',
    change24h: -0.28,
    volume: 64.0,
    category: 'Tier-3',
    couponPercent: 8.60,
    paymentFrequency: 'Annual',
    taxStatus: 'Tax-Free',
    projectsFunded: ['Dehradun smart LED project', 'Landslide retaining grid structures'],
    capitalRaisedCr: 80,
    description: 'Backed by state environmental funding matching pools and property taxing grids.',
    allTimeHigh: 100400,
    allTimeLow: 98110
  }
];

// All 28 States & UTs with high-fidelity analytics (Cr = Crores, 1 Cr = 10 Million INR)
export const STATE_METRICS: StateMetrics[] = [
  { state: 'Andhra Pradesh', totalBondsOutstanding: 3, totalFundsRaisedCr: 350, avgYield: 8.42, corporationsCount: 13, riskFactor: 3, defaultProbabilityPercent: 2.1 },
  { state: 'Arunachal Pradesh', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 2, riskFactor: 4, defaultProbabilityPercent: 5.0 },
  { state: 'Assam', totalBondsOutstanding: 1, totalFundsRaisedCr: 75, avgYield: 8.65, corporationsCount: 4, riskFactor: 3, defaultProbabilityPercent: 3.5 },
  { state: 'Bihar', totalBondsOutstanding: 2, totalFundsRaisedCr: 180, avgYield: 9.15, corporationsCount: 18, riskFactor: 4, defaultProbabilityPercent: 6.8 },
  { state: 'Chhattisgarh', totalBondsOutstanding: 2, totalFundsRaisedCr: 180, avgYield: 8.35, corporationsCount: 14, riskFactor: 2, defaultProbabilityPercent: 1.8 },
  { state: 'Goa', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 1, defaultProbabilityPercent: 0.5 },
  { state: 'Gujarat', totalBondsOutstanding: 8, totalFundsRaisedCr: 1550, avgYield: 7.55, corporationsCount: 8, riskFactor: 1, defaultProbabilityPercent: 0.1 },
  { state: 'Haryana', totalBondsOutstanding: 4, totalFundsRaisedCr: 780, avgYield: 7.95, corporationsCount: 11, riskFactor: 1, defaultProbabilityPercent: 0.4 },
  { state: 'Himachal Pradesh', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 5, riskFactor: 2, defaultProbabilityPercent: 1.5 },
  { state: 'Jharkhand', totalBondsOutstanding: 1, totalFundsRaisedCr: 120, avgYield: 8.78, corporationsCount: 9, riskFactor: 3, defaultProbabilityPercent: 4.2 },
  { state: 'Karnataka', totalBondsOutstanding: 5, totalFundsRaisedCr: 1400, avgYield: 7.92, corporationsCount: 11, riskFactor: 2, defaultProbabilityPercent: 0.8 },
  { state: 'Kerala', totalBondsOutstanding: 3, totalFundsRaisedCr: 350, avgYield: 8.01, corporationsCount: 6, riskFactor: 2, defaultProbabilityPercent: 1.2 },
  { state: 'Madhya Pradesh', totalBondsOutstanding: 5, totalFundsRaisedCr: 840, avgYield: 7.82, corporationsCount: 16, riskFactor: 2, defaultProbabilityPercent: 1.1 },
  { state: 'Maharashtra', totalBondsOutstanding: 12, totalFundsRaisedCr: 3650, avgYield: 7.68, corporationsCount: 28, riskFactor: 1, defaultProbabilityPercent: 0.2 },
  { state: 'Manipur', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 5, defaultProbabilityPercent: 12.0 },
  { state: 'Meghalaya', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 3, defaultProbabilityPercent: 4.8 },
  { state: 'Mizoram', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 4, defaultProbabilityPercent: 6.5 },
  { state: 'Nagaland', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 5, defaultProbabilityPercent: 10.0 },
  { state: 'Odisha', totalBondsOutstanding: 2, totalFundsRaisedCr: 200, avgYield: 7.80, corporationsCount: 5, riskFactor: 1, defaultProbabilityPercent: 0.3 },
  { state: 'Punjab', totalBondsOutstanding: 3, totalFundsRaisedCr: 232, avgYield: 8.45, corporationsCount: 13, riskFactor: 3, defaultProbabilityPercent: 3.8 },
  { state: 'Rajasthan', totalBondsOutstanding: 2, totalFundsRaisedCr: 240, avgYield: 8.28, corporationsCount: 10, riskFactor: 3, defaultProbabilityPercent: 2.5 },
  { state: 'Sikkim', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 2, defaultProbabilityPercent: 1.0 },
  { state: 'Tamil Nadu', totalBondsOutstanding: 4, totalFundsRaisedCr: 680, avgYield: 8.05, corporationsCount: 20, riskFactor: 1, defaultProbabilityPercent: 0.5 },
  { state: 'Telangana', totalBondsOutstanding: 6, totalFundsRaisedCr: 1900, avgYield: 7.72, corporationsCount: 13, riskFactor: 2, defaultProbabilityPercent: 0.9 },
  { state: 'Tripura', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 4, defaultProbabilityPercent: 5.5 },
  { state: 'Uttar Pradesh', totalBondsOutstanding: 6, totalFundsRaisedCr: 950, avgYield: 8.35, corporationsCount: 17, riskFactor: 3, defaultProbabilityPercent: 2.8 },
  { state: 'Uttarakhand', totalBondsOutstanding: 1, totalFundsRaisedCr: 80, avgYield: 8.68, corporationsCount: 9, riskFactor: 2, defaultProbabilityPercent: 2.0 },
  { state: 'West Bengal', totalBondsOutstanding: 2, totalFundsRaisedCr: 400, avgYield: 8.72, corporationsCount: 7, riskFactor: 3, defaultProbabilityPercent: 4.5 },
  // Major UTs
  { state: 'Delhi', totalBondsOutstanding: 3, totalFundsRaisedCr: 950, avgYield: 7.52, corporationsCount: 5, riskFactor: 1, defaultProbabilityPercent: 0.2 },
  { state: 'Chandigarh', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 1, defaultProbabilityPercent: 0.3 },
  { state: 'Jammu & Kashmir', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 2, riskFactor: 4, defaultProbabilityPercent: 7.2 },
  { state: 'Puducherry', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 2, defaultProbabilityPercent: 1.4 },
  { state: 'Ladakh', totalBondsOutstanding: 0, totalFundsRaisedCr: 0, avgYield: 0, corporationsCount: 1, riskFactor: 3, defaultProbabilityPercent: 3.5 }
];

export const CORPORATIONS_CATALOG = [
  { name: 'Brihanmumbai Municipal Corporation', short: 'BMC', state: 'Maharashtra', est: 1888, popServed: '124 Lakhs', bondsCount: 4, totalFundsCr: 2100, rating: 'AAA', website: 'https://portal.mcgm.gov.in', contact: 'commissioner@mcgm.gov.in' },
  { name: 'Bruhat Bengaluru Mahanagara Palike', short: 'BBMP', state: 'Karnataka', est: 2007, popServed: '84 Lakhs', bondsCount: 3, totalFundsCr: 1200, rating: 'AA', website: 'https://bbmp.gov.in', contact: 'comm@bbmp.gov.in' },
  { name: 'Greater Hyderabad Municipal Corporation', short: 'GHMC', state: 'Telangana', est: 2007, popServed: '69 Lakhs', bondsCount: 3, totalFundsCr: 1400, rating: 'AA', website: 'https://www.ghmc.gov.in', contact: 'comm-ghmc@telangana.gov.in' },
  { name: 'Ahmedabad Municipal Corporation', short: 'AMC', state: 'Gujarat', est: 1950, popServed: '56 Lakhs', bondsCount: 4, totalFundsCr: 950, rating: 'AA+', website: 'https://ahmedabadcity.gov.in', contact: 'mc@ahmedabadcity.gov.in' },
  { name: 'Pune Municipal Corporation', short: 'PMC', state: 'Maharashtra', est: 1950, popServed: '31 Lakhs', bondsCount: 2, totalFundsCr: 600, rating: 'AA', website: 'https://www.pmc.gov.in', contact: 'commissioner@pmc.gov.in' },
  { name: 'Surat Municipal Corporation', short: 'SMC', state: 'Gujarat', est: 1966, popServed: '44 Lakhs', bondsCount: 2, totalFundsCr: 700, rating: 'AA+', website: 'https://www.suratmunicipal.gov.in', contact: 'commissioner@suratmunicipal.org' },
  { name: 'Kolkata Municipal Corporation', short: 'KMC', state: 'West Bengal', est: 1876, popServed: '45 Lakhs', bondsCount: 2, totalFundsCr: 400, rating: 'AA-', website: 'https://www.kmcgov.in', contact: 'mc@kmcgov.in' },
  { name: 'Greater Chennai Corporation', short: 'GCC', state: 'Tamil Nadu', est: 1688, popServed: '70 Lakhs', bondsCount: 2, totalFundsCr: 550, rating: 'AA+', website: 'https://www.chennaicorporation.gov.in', contact: 'commissioner@chennaicorporation.gov.in' },
  { name: 'Lucknow Municipal Corporation', short: 'LMC', state: 'Uttar Pradesh', est: 1959, popServed: '28 Lakhs', bondsCount: 2, totalFundsCr: 350, rating: 'AA', website: 'http://lmc.up.nic.in', contact: 'mc-lucknow@up.gov.in' },
  { name: 'Indore Municipal Corporation', short: 'IMC', state: 'Madhya Pradesh', est: 1956, popServed: '20 Lakhs', bondsCount: 2, totalFundsCr: 450, rating: 'AA+', website: 'https://www.imcindore.org', contact: 'smartcity@imcindore.org' },
  { name: 'Municipal Corporation of Gurugram', short: 'MCG', state: 'Haryana', est: 2008, popServed: '15 Lakhs', bondsCount: 2, totalFundsCr: 500, rating: 'AA+', website: 'https://www.mcg.gov.in', contact: 'commissioner@mcg.gov.in' },
  { name: 'Patna Municipal Corporation', short: 'PAT', state: 'Bihar', est: 1952, popServed: '21 Lakhs', bondsCount: 1, totalFundsCr: 120, rating: 'A', website: 'https://www.pmcbihar.gov.in', contact: 'comm@pmcbihar.gov.in' },
  { name: 'Bhubaneswar Municipal Corporation', short: 'BHU', state: 'Odisha', est: 1994, popServed: '9 Lakhs', bondsCount: 1, totalFundsCr: 100, rating: 'AA', website: 'https://bmc.gov.in', contact: 'comm@bmc.gov.in' },
  { name: 'New Delhi Municipal Council', short: 'NDMC', state: 'Delhi', est: 1913, popServed: '3 Lakhs', bondsCount: 1, totalFundsCr: 150, rating: 'AAA', website: 'https://www.ndmc.gov.in', contact: 'chairman@ndmc.gov.in' }
];

export const MOCK_RATING_HISTORY: Record<string, { date: string; rating: CreditRating; agency: RatingAgency; outlook: 'Stable' | 'Positive' | 'Negative' }[]> = {
  'BND-BMC-001': [
    { date: '2026-01-10', rating: 'AAA', agency: 'CRISIL', outlook: 'Stable' },
    { date: '2024-05-15', rating: 'AAA', agency: 'CRISIL', outlook: 'Stable' },
    { date: '2022-11-20', rating: 'AA+', agency: 'CRISIL', outlook: 'Positive' },
  ],
  'BND-BBMP-001': [
    { date: '2025-11-05', rating: 'AA', agency: 'CRISIL', outlook: 'Stable' },
    { date: '2023-08-12', rating: 'AA-', agency: 'CRISIL', outlook: 'Positive' },
    { date: '2021-04-10', rating: 'AA-', agency: 'CRISIL', outlook: 'Stable' },
  ],
  'BND-IMC-001': [
    { date: '2026-03-01', rating: 'AA+', agency: 'CRISIL', outlook: 'Stable' },
    { date: '2024-02-18', rating: 'AA+', agency: 'CRISIL', outlook: 'Stable' },
    { date: '2022-09-12', rating: 'AA', agency: 'CRISIL', outlook: 'Positive' },
  ],
  'BND-KMC-001': [
    { date: '2026-02-15', rating: 'AA-', agency: 'ICRA', outlook: 'Negative' },
    { date: '2024-06-20', rating: 'AA-', agency: 'ICRA', outlook: 'Stable' },
    { date: '2022-12-10', rating: 'AA-', agency: 'ICRA', outlook: 'Stable' },
  ],
};

// Top news ticker feed for terminal feeling
export const TERMINAL_NEWS = [
  { id: 'N1', text: 'REUTERS: SEBI approves municipal bond issuances via simplified public offer guidelines.', severity: 'normal', time: '10m ago' },
  { id: 'N2', text: 'ALERT: Indore Municipal Corporation Green Bonds 8.25% premium trade volumes cross ₹5 Cr in early session.', severity: 'high', time: '22m ago' },
  { id: 'N3', text: 'FINANCIAL EXPRESS: Maharashtra corporations lead outstanding debt liability at ₹3,650 Cr.', severity: 'normal', time: '1h ago' },
  { id: 'N4', text: 'CRISIL: Upgrades Lucknow Municipal to AA outlook Positive citing enhanced ring-fencing mechanism.', severity: 'high', time: '2h ago' },
  { id: 'N5', text: 'MINISTRY OF HOUSING: Smart City funds matching pool release scheduled for Tier-2 corporations next week.', severity: 'normal', time: '4h ago' },
  { id: 'N6', text: 'RBI REPORT: Municipal bonds yield curves flatten slightly matching G-Sec spreads around 110 bps.', severity: 'normal', time: '5h ago' }
];
